name: CI

on: [push]

jobs:
  image_scan:
    name: Build Image and Run Image Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker-practice/actions-setup-docker@v1
      with:
        docker_version: '20.10.7'

    - name: Build Docker Image
      run: docker build -f Dockerfile -t ${{ secrets.REPO_USER }}/myapp:latest .

    - name: Log in to DockerHub
      run: echo "${{ secrets.REPO_PWD }}" | docker login -u "${{ secrets.REPO_USER }}" --password-stdin

    - name: Push Docker Image
      run: |
        docker push "${{ secrets.REPO_USER }}/myapp:latest"

    - name: Pull Docker Image
      run: docker pull ${{ secrets.REPO_USER }}/myapp:latest

    - name: Set TMPDIR
      run: export TMPDIR=/home/runner/tmp && mkdir -p /home/runner/tmp

    - name: Docker Scout Scan
      uses: docker/scout-action@v1.0.9
      with:
        dockerhub-user: ${{ secrets.REPO_USER }}
        dockerhub-password: ${{ secrets.REPO_PWD }}
        command: quickview,cves
        image: ${{ secrets.REPO_USER }}/myapp:latest
        only-severities: critical,high
        sarif-file: scout-report.sarif
      env:
        TMPDIR: /home/runner/tmp

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: docker-scout-findings
        path: scout-report.sarif
